spring.datasource.url=jdbc:postgresql://localhost:5432/teste
spring.datasource.username=seu_usuario
spring.datasource.password=sua_senha
spring.datasource.hikari.allow-pool-suspension=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=MYJWTSECRET
jwt.expiration=3600000

server.port=8081

# Specify explicitly the dialect (here for PostgreSQL, adapt for yourdatabase)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Disable Hibernate usage of JDBC metadata
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

# Database initialization should typically be performed outside of Springlifecycle
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never